export const LOGIN = 'LOGIN';
export const CURRENCY_LOAD = 'CURRENCY_LOAD';
export const CURRENCY_LOAD_SUCCESS = 'CURRENCY_LOAD_SUCCESS';
export const CURRENCY_LOAD_FAILURE = 'CURRENCY_LOAD_FAILURE';
export const ADD_EXPENSE = 'ADD_EXPENSE';
