const types = {
  LOGIN_INFO: 'LOGIN_INFO',
  WALLET_INFO: 'WALLET_INFO',
  GET_WALLET_API_SUCCESS: 'GET_WALLET_API_SUCCESS',
  GET_WALLET_API_FAILED: 'GET_WALLET_API_FAILED',
  LOADING_API: 'LOADING_API',
  GET_EXPENSES: 'GET_EXPENSES',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
  EDIT_EXPENSE: 'EDIT_EXPENSE',
  SET_NEW_EXPENSE: 'SET_NEW_EXPENSE',
  LOAD_EDITED_EXPENSE: 'LOAD_EDITED_EXPENSE',
};

export default types;
